language: csharp
solution: VectorRumble.Shared.sln

os:
  - osx

env: 
  global: 
    - Configuration=Release
    - Platform=x86

install:
  - wget -P downloads -O MonoGame.pkg "http://teamcity.monogame.net/guestAuth/repository/download/MonoGame_PackageMacAndLinux/.lastSuccessful/MonoGame.pkg?branch_MonoGame=%3Cdefault%3E"
  - sudo installer -pkg "downloads/MonoGame.pkg" -target / 

script:
  - xbuild VectorRumble.Desktop/VectorRumble.Desktop.csproj /p:Platform=$(Platform) /p:Configuration=$(Configuration) /v:d /t:Build 
