language: csharp
solution: VectorRumble.sln
os:
- osx
env:
  global:
  - Configuration=Release
  - secure: IZMfnkwbbAUs4SK3Fng6pMEqQlQABYrYejli1OtlU4m7LCM0QtoQjsaXgP81bIQypRoldmE1Is5q/MU/0j+XEzYGvGL1uZ4w1mSbLn4eepHb1BpmzepHE776xYK+G0JubT8LHHApIrb1Ung8jykGgr1nEzwP3klyGmUvGDlx3EHoiitw/Ji9f/UkwLvYTBuHxi27/0ENygu4/Nm8PLIOcMPE1OvqthDNSvCq+36OEv5v73XAeN3JoiatMgoXAflQW+AfygfQQg+HiaFwtMBl5pRaUMm8nUgqN7/b+3ZYmix0Vgeu7d0MDgXeMtIaANFFxzbSE9NayJEdAwlReyEFyu3eQlN6Ifa7mhszRWmUrm/eZiifvfnZCqnGDr3bcXddHd2PULN4UDcBhIdhrOpI2jWr8czJHM3psi+wblCd7+/L73PKDZBD1OkgVg4/Cy1Bl/0cXCUqkvklU94xG44tTKskU1ZMsIKaVvkR7RLxbGFvFZXtkUT06m1IiEDFfhu5WAMI0YiMKh4gpv4mryGuDQjTJ2R2XtZ3a84T7BysPP6uhmRkIqHs7FNvr3Phz45N/v7x8dE8daCRbEjHVKs7W9Ff/3apigja8NErKl6tk1KXDNfpqRjoSBJ1/TeuS6WFHxTStox6RCTwnZWQn2g7HNu66x+MzFjpnXdDJ2NLqeI= 
install:
- wget -O MonoGame.pkg https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/MonoGame.pkg
#- wget -O MonoGame.pkg "http://teamcity.monogame.net/guestAuth/repository/download/MonoGame_PackageMacAndLinux/.lastSuccessful/MonoGame.pkg?branch_MonoGame=%3Cdefault%3E"
- sudo installer -pkg "MonoGame.pkg" -target /
- wget -O butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default
- unzip butler.zip
- chmod +x butler
- ./butler -V
script:
- nuget restore VectorRumble.sln
- msbuild VectorRumble.Desktop/VectorRumble.Desktop.csproj /p:Configuration=Release /v:d /t:Build
- msbuild VectorRumble.Desktop/VectorRumble.Desktop.csproj /p:Configuration=Release /v:d /t:GetBuildVersion
deploy:
- provider: releases
  api_key:
    secure: "UdhT/6mDyRq2r3Tby9GanB0V0vkngGg/KMFMQTDVNx3BublwDpnp3MDW+mkLZdMndmQmCFhXjKDM3KAg5XZOH4eWwV9+5EYQ+OSmYYjSdQPPnHiHwV4CqjdDsJHvcHOwXVdUC88Aj5dNHKUWGP1CPi03NLRS2jh59QTqFfvKh1YB8f6WMHlI5zu6AaP1BTeqRRLZCE5UFFgOzTj3hbWdq9m8euOcde90ptQEQpQDXuVLkNOCPceJNXFyGjiiZVniwxSHUr3XT47Z3BR4VEG4HQQFhr0QvhEMMorJ1qY0iBx4hWsNsX+9iQV0nDwHUNaKZApbak2Sjt5Bq4irndZWpelVJ5X7ov1DxMf+zWzSPQbSX/fPiHBbXsRRgCvC+IDWWv5Rx4D/MmyqcPkfFAkB9lxK+Wlu9D34VP6Rst6l78D2vy9nfezkZrQ5d00s79uLCFzojjJHuMjMfEWOq0T9NROugGM3rL/qbPQfnFnUSjVqHmG0+BOwSAyhw70H5jnEp1paKTP8ckiURDgB63u4mOyUL0isGlbanW/lTIVytXMgKy4VDehXJDec80nRdSLO5vfYZIC1Snx4iaURqGoKC0D+Xlq4ByYSNMplu9tmfudK/hk8LEuxZsEZ8U6Qk8GtMhSt4hsfivWzRsOGWBI7tZIixCYZfZ5GB9HtcDPTung="
  file: VectorRumble.Desktop/bin/Release/VectorRumble-MacOS-Steam.zip
  skip_cleanup: true 
  on:
    repo: infinitespace-studios/VectorRumble
    tags: true
- provider: releases
  api_key:
    secure: "UdhT/6mDyRq2r3Tby9GanB0V0vkngGg/KMFMQTDVNx3BublwDpnp3MDW+mkLZdMndmQmCFhXjKDM3KAg5XZOH4eWwV9+5EYQ+OSmYYjSdQPPnHiHwV4CqjdDsJHvcHOwXVdUC88Aj5dNHKUWGP1CPi03NLRS2jh59QTqFfvKh1YB8f6WMHlI5zu6AaP1BTeqRRLZCE5UFFgOzTj3hbWdq9m8euOcde90ptQEQpQDXuVLkNOCPceJNXFyGjiiZVniwxSHUr3XT47Z3BR4VEG4HQQFhr0QvhEMMorJ1qY0iBx4hWsNsX+9iQV0nDwHUNaKZApbak2Sjt5Bq4irndZWpelVJ5X7ov1DxMf+zWzSPQbSX/fPiHBbXsRRgCvC+IDWWv5Rx4D/MmyqcPkfFAkB9lxK+Wlu9D34VP6Rst6l78D2vy9nfezkZrQ5d00s79uLCFzojjJHuMjMfEWOq0T9NROugGM3rL/qbPQfnFnUSjVqHmG0+BOwSAyhw70H5jnEp1paKTP8ckiURDgB63u4mOyUL0isGlbanW/lTIVytXMgKy4VDehXJDec80nRdSLO5vfYZIC1Snx4iaURqGoKC0D+Xlq4ByYSNMplu9tmfudK/hk8LEuxZsEZ8U6Qk8GtMhSt4hsfivWzRsOGWBI7tZIixCYZfZ5GB9HtcDPTung="
  file: VectorRumble.Desktop/bin/Release/VectorRumble-Windows-Steam.zip
  skip_cleanup: true 
  on:
    repo: infinitespace-studios/VectorRumble
    tags: true
- provider: releases
  api_key:
    secure: "UdhT/6mDyRq2r3Tby9GanB0V0vkngGg/KMFMQTDVNx3BublwDpnp3MDW+mkLZdMndmQmCFhXjKDM3KAg5XZOH4eWwV9+5EYQ+OSmYYjSdQPPnHiHwV4CqjdDsJHvcHOwXVdUC88Aj5dNHKUWGP1CPi03NLRS2jh59QTqFfvKh1YB8f6WMHlI5zu6AaP1BTeqRRLZCE5UFFgOzTj3hbWdq9m8euOcde90ptQEQpQDXuVLkNOCPceJNXFyGjiiZVniwxSHUr3XT47Z3BR4VEG4HQQFhr0QvhEMMorJ1qY0iBx4hWsNsX+9iQV0nDwHUNaKZApbak2Sjt5Bq4irndZWpelVJ5X7ov1DxMf+zWzSPQbSX/fPiHBbXsRRgCvC+IDWWv5Rx4D/MmyqcPkfFAkB9lxK+Wlu9D34VP6Rst6l78D2vy9nfezkZrQ5d00s79uLCFzojjJHuMjMfEWOq0T9NROugGM3rL/qbPQfnFnUSjVqHmG0+BOwSAyhw70H5jnEp1paKTP8ckiURDgB63u4mOyUL0isGlbanW/lTIVytXMgKy4VDehXJDec80nRdSLO5vfYZIC1Snx4iaURqGoKC0D+Xlq4ByYSNMplu9tmfudK/hk8LEuxZsEZ8U6Qk8GtMhSt4hsfivWzRsOGWBI7tZIixCYZfZ5GB9HtcDPTung="
  file: VectorRumble.Desktop/bin/Release/VectorRumble-Linux-Steam.zip
  skip_cleanup: true 
  on:
    repo: infinitespace-studios/VectorRumble
    tags: true
- provider: releases
  api_key:
    secure: "UdhT/6mDyRq2r3Tby9GanB0V0vkngGg/KMFMQTDVNx3BublwDpnp3MDW+mkLZdMndmQmCFhXjKDM3KAg5XZOH4eWwV9+5EYQ+OSmYYjSdQPPnHiHwV4CqjdDsJHvcHOwXVdUC88Aj5dNHKUWGP1CPi03NLRS2jh59QTqFfvKh1YB8f6WMHlI5zu6AaP1BTeqRRLZCE5UFFgOzTj3hbWdq9m8euOcde90ptQEQpQDXuVLkNOCPceJNXFyGjiiZVniwxSHUr3XT47Z3BR4VEG4HQQFhr0QvhEMMorJ1qY0iBx4hWsNsX+9iQV0nDwHUNaKZApbak2Sjt5Bq4irndZWpelVJ5X7ov1DxMf+zWzSPQbSX/fPiHBbXsRRgCvC+IDWWv5Rx4D/MmyqcPkfFAkB9lxK+Wlu9D34VP6Rst6l78D2vy9nfezkZrQ5d00s79uLCFzojjJHuMjMfEWOq0T9NROugGM3rL/qbPQfnFnUSjVqHmG0+BOwSAyhw70H5jnEp1paKTP8ckiURDgB63u4mOyUL0isGlbanW/lTIVytXMgKy4VDehXJDec80nRdSLO5vfYZIC1Snx4iaURqGoKC0D+Xlq4ByYSNMplu9tmfudK/hk8LEuxZsEZ8U6Qk8GtMhSt4hsfivWzRsOGWBI7tZIixCYZfZ5GB9HtcDPTung="
  file: VectorRumble.Desktop/bin/Release/VectorRumble-MacOS.zip
  skip_cleanup: true 
  on:
    repo: infinitespace-studios/VectorRumble
    tags: true
- provider: releases
  api_key:
    secure: "UdhT/6mDyRq2r3Tby9GanB0V0vkngGg/KMFMQTDVNx3BublwDpnp3MDW+mkLZdMndmQmCFhXjKDM3KAg5XZOH4eWwV9+5EYQ+OSmYYjSdQPPnHiHwV4CqjdDsJHvcHOwXVdUC88Aj5dNHKUWGP1CPi03NLRS2jh59QTqFfvKh1YB8f6WMHlI5zu6AaP1BTeqRRLZCE5UFFgOzTj3hbWdq9m8euOcde90ptQEQpQDXuVLkNOCPceJNXFyGjiiZVniwxSHUr3XT47Z3BR4VEG4HQQFhr0QvhEMMorJ1qY0iBx4hWsNsX+9iQV0nDwHUNaKZApbak2Sjt5Bq4irndZWpelVJ5X7ov1DxMf+zWzSPQbSX/fPiHBbXsRRgCvC+IDWWv5Rx4D/MmyqcPkfFAkB9lxK+Wlu9D34VP6Rst6l78D2vy9nfezkZrQ5d00s79uLCFzojjJHuMjMfEWOq0T9NROugGM3rL/qbPQfnFnUSjVqHmG0+BOwSAyhw70H5jnEp1paKTP8ckiURDgB63u4mOyUL0isGlbanW/lTIVytXMgKy4VDehXJDec80nRdSLO5vfYZIC1Snx4iaURqGoKC0D+Xlq4ByYSNMplu9tmfudK/hk8LEuxZsEZ8U6Qk8GtMhSt4hsfivWzRsOGWBI7tZIixCYZfZ5GB9HtcDPTung="
  file: VectorRumble.Desktop/bin/Release/VectorRumble-Windows.zip
  skip_cleanup: true 
  on:
    repo: infinitespace-studios/VectorRumble
    tags: true
- provider: releases
  api_key:
    secure: "UdhT/6mDyRq2r3Tby9GanB0V0vkngGg/KMFMQTDVNx3BublwDpnp3MDW+mkLZdMndmQmCFhXjKDM3KAg5XZOH4eWwV9+5EYQ+OSmYYjSdQPPnHiHwV4CqjdDsJHvcHOwXVdUC88Aj5dNHKUWGP1CPi03NLRS2jh59QTqFfvKh1YB8f6WMHlI5zu6AaP1BTeqRRLZCE5UFFgOzTj3hbWdq9m8euOcde90ptQEQpQDXuVLkNOCPceJNXFyGjiiZVniwxSHUr3XT47Z3BR4VEG4HQQFhr0QvhEMMorJ1qY0iBx4hWsNsX+9iQV0nDwHUNaKZApbak2Sjt5Bq4irndZWpelVJ5X7ov1DxMf+zWzSPQbSX/fPiHBbXsRRgCvC+IDWWv5Rx4D/MmyqcPkfFAkB9lxK+Wlu9D34VP6Rst6l78D2vy9nfezkZrQ5d00s79uLCFzojjJHuMjMfEWOq0T9NROugGM3rL/qbPQfnFnUSjVqHmG0+BOwSAyhw70H5jnEp1paKTP8ckiURDgB63u4mOyUL0isGlbanW/lTIVytXMgKy4VDehXJDec80nRdSLO5vfYZIC1Snx4iaURqGoKC0D+Xlq4ByYSNMplu9tmfudK/hk8LEuxZsEZ8U6Qk8GtMhSt4hsfivWzRsOGWBI7tZIixCYZfZ5GB9HtcDPTung="
  file: VectorRumble.Desktop/bin/Release/VectorRumble-Linux.zip
  skip_cleanup: true 
  on:
    repo: infinitespace-studios/VectorRumble
    tags: true
- provider: releases
  api_key:
    secure: "UdhT/6mDyRq2r3Tby9GanB0V0vkngGg/KMFMQTDVNx3BublwDpnp3MDW+mkLZdMndmQmCFhXjKDM3KAg5XZOH4eWwV9+5EYQ+OSmYYjSdQPPnHiHwV4CqjdDsJHvcHOwXVdUC88Aj5dNHKUWGP1CPi03NLRS2jh59QTqFfvKh1YB8f6WMHlI5zu6AaP1BTeqRRLZCE5UFFgOzTj3hbWdq9m8euOcde90ptQEQpQDXuVLkNOCPceJNXFyGjiiZVniwxSHUr3XT47Z3BR4VEG4HQQFhr0QvhEMMorJ1qY0iBx4hWsNsX+9iQV0nDwHUNaKZApbak2Sjt5Bq4irndZWpelVJ5X7ov1DxMf+zWzSPQbSX/fPiHBbXsRRgCvC+IDWWv5Rx4D/MmyqcPkfFAkB9lxK+Wlu9D34VP6Rst6l78D2vy9nfezkZrQ5d00s79uLCFzojjJHuMjMfEWOq0T9NROugGM3rL/qbPQfnFnUSjVqHmG0+BOwSAyhw70H5jnEp1paKTP8ckiURDgB63u4mOyUL0isGlbanW/lTIVytXMgKy4VDehXJDec80nRdSLO5vfYZIC1Snx4iaURqGoKC0D+Xlq4ByYSNMplu9tmfudK/hk8LEuxZsEZ8U6Qk8GtMhSt4hsfivWzRsOGWBI7tZIixCYZfZ5GB9HtcDPTung="
  file: VectorRumble.Desktop/bin/Release/VectorRumble-MacOS-AppStore.zip
  skip_cleanup: true 
  on:
    repo: infinitespace-studios/VectorRumble
    tags: true
- provider: script
  script:
  - ./butler push VectorRumble.Desktop/bin/Release/VectorRumble-MacOS.zip infinitespace-studios/vector-rumble:osx-alpha --userversion-file VectorRumble.Desktop/appversion.txt
  - ./butler push VectorRumble.Desktop/bin/Release/VectorRumble-Linux.zip infinitespace-studios/vector-rumble:linux-alpha --userversion-file VectorRumble.Desktop/appversion.txt
  - ./butler push VectorRumble.Desktop/bin/Release/VectorRumble-Windows.zip infinitespace-studios/vector-rumble:windows-alpha --userversion-file VectorRumble.Desktop/appversion.txt
  skip_cleanup: true 
  on:
    repo: infinitespace-studios/VectorRumble
    tags: true
