language: csharp
solution: VectorRumble.sln
os:
- osx
env:
  global:
  - Configuration=Release
install:
- wget -O MonoGame.pkg "http://teamcity.monogame.net/guestAuth/repository/download/MonoGame_PackageMacAndLinux/.lastSuccessful/MonoGame.pkg?branch_MonoGame=%3Cdefault%3E"
- sudo installer -pkg "MonoGame.pkg" -target /
- wget -O butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default
- unzip butler.zip
- chmod +x butler
- ./butler -V
script:
- nuget restore VectorRumble.sln
- msbuild VectorRumble.Desktop/VectorRumble.Desktop.csproj /p:Configuration=Release /v:d /t:Build
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: IPHHTN2a/gz9ulPHPQ/75VM/CxUC80gjiwPoeFDoAbNJa09MYav3OGAAUsqkpCkIPrO/sVNDvZ2Wm+IkYtR7B+DFBPMbT2rGplWLhvkMypuGDUQvxOWUTXoU531pwAXFPhjC9Mgud/WEMfohyJ9R+q/6P6dO0Zfnd9A9OUnSXSnxdfxrdqnJFhPuyAqjYIWVoanN8Y0jrRZ9idqV7gjrgYP2EsmeF9Av1SuINzQ7a4Sr7NSIvlz/gksKPF8VFpT9SZJwdZlf24cBZeosP3CXRKKrs1IvICqkcf5gI3YVoZlAaIIJVYpz0r2pVNiHsQ5SsAgz+svrHEjH7BfjsfGKMbfyXLN9UJEBSO6Z8xLcZ60H5iUWh6xu91LHoiHs6mfg5ntGKx1HitYCkEQ2AKnteS6cuI/ZsVvkoA7+JZh+IrOUvnsH3PJbj23HVlf7ure9qbGvUTyFLwEyr7JgJENzSrt46goRDmlxYdcw6UuPWNW+BLHyDmWp7c3y2X5hxV4IlxFdjKafha7zgwgabRcBgmcO8O4rOn17haYsTZ66zGat97MmsNnPmcaws5ngJl8Yyt7cUO5D11ESMFcIneOk2dgMzXZzS6LRIHFJ1XdYEwWvQ+f1kqnLaFuQ5cig8CBgQPkfkHPjMQ5ib8QgAj5p2vz7fiQYwoJ8XTtFrsRgvbU=
    file:
      - VectorRumble.Desktop/bin/Release/VectorRumble-MacOS-Steam.zip
      - VectorRumble.Desktop/bin/Release/VectorRumble-Linux-Steam.zip
      - VectorRumble.Desktop/bin/Release/VectorRumble-Windows-Steam.zip 
      - VectorRumble.Desktop/bin/Release/VectorRumble-MacOS.zip
      - VectorRumble.Desktop/bin/Release/VectorRumble-Windows.zip
      - VectorRumble.Desktop/bin/Release/VectorRumble-Linux.zip 
      - VectorRumble.Desktop/bin/Release/VectorRumble-MacOS-AppStore.zip 
    on:
      repo: infinitespace-studios/VectorRumble
      tags: true
  provider: script
    skip_cleanup: true
    script:
    - ./butler -V
    env:
    - secure: IZMfnkwbbAUs4SK3Fng6pMEqQlQABYrYejli1OtlU4m7LCM0QtoQjsaXgP81bIQypRoldmE1Is5q/MU/0j+XEzYGvGL1uZ4w1mSbLn4eepHb1BpmzepHE776xYK+G0JubT8LHHApIrb1Ung8jykGgr1nEzwP3klyGmUvGDlx3EHoiitw/Ji9f/UkwLvYTBuHxi27/0ENygu4/Nm8PLIOcMPE1OvqthDNSvCq+36OEv5v73XAeN3JoiatMgoXAflQW+AfygfQQg+HiaFwtMBl5pRaUMm8nUgqN7/b+3ZYmix0Vgeu7d0MDgXeMtIaANFFxzbSE9NayJEdAwlReyEFyu3eQlN6Ifa7mhszRWmUrm/eZiifvfnZCqnGDr3bcXddHd2PULN4UDcBhIdhrOpI2jWr8czJHM3psi+wblCd7+/L73PKDZBD1OkgVg4/Cy1Bl/0cXCUqkvklU94xG44tTKskU1ZMsIKaVvkR7RLxbGFvFZXtkUT06m1IiEDFfhu5WAMI0YiMKh4gpv4mryGuDQjTJ2R2XtZ3a84T7BysPP6uhmRkIqHs7FNvr3Phz45N/v7x8dE8daCRbEjHVKs7W9Ff/3apigja8NErKl6tk1KXDNfpqRjoSBJ1/TeuS6WFHxTStox6RCTwnZWQn2g7HNu66x+MzFjpnXdDJ2NLqeI= 
    on:
      repo: infinitespace-studios/VectorRumble
      tags: true
