language: csharp
solution: VectorRumble.Shared.sln

env: 
  global: 
    - Configuration=Release

install:
  wget nc -P downloads "http://teamcity.monogame.net/guestAuth/repository/download/MonoGame_PackageMacAndLinux/.lastSuccessful/MonoGame.pkg"
  sudo installer -pkg "downloads/MonoGame.pkg" -target / 

script:
  xbuild VectorRumble.Desktop/VectorRumble.Desktop.csproj /p:Configuration-$(Configuration) /v:d /t:Build 
